export const GOOGLE = "google";
export const FACEBOOK = "facebook";
export const TWITTER = "twitter";
export const ACCESS_TOKEN_KEY = "accessToken";
export const MIN_NAME_LENGTH = 2;
export const MIN_CITY_LENGTH = 3;
export const MIN_PASSWORD_LENGTH = 6;
export const POLLER_INTERVAL = 3000;
export const ORDER_STATUSES = ["order", "delivery", "paid"];
export const ORDER_STATUSES_DELIVERY = ["delivery", "paid"];
export const ORDER_STATUSES_COOK = ["order", "delivery"];
export const UPLOAD_URL = "../img_dishes"
export const MIN_ID = 100;
export const MAX_ID = 9999;
export const MENU_FORM = ["first-dishes", "rolls", "baked rolls", "sushi", 'drinks'];
export const CURRENCY = "$"
export const PHONE_NUMBER = 'tel:1800800859'
export const TELEPHONE = "telephone"
export const PCS = ' pcs';
export const ROLES = ['customer', 'courier', 'cook', 'owner', 'manager']
export const TABLE_ROLES = ['All', 'customer', 'courier', 'cook', 'owner', 'manager']
export const TABLE_ORDER_STATUSES = ["All", "order", "delivery", "paid"];
export const TABLE_ORDER_STATUSES_DELIVERY = ["All", "delivery", "paid"];
export const TABLE_ORDER_STATUSES_COOK = ["All", "order"];